apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n5jr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-n5jr@sha256:dacf1825034b2ed4c25c421ad76627f1cca974d125ccd125eebe25bd4372f3ca
        name: my-nodejs
        resources: {}
status: {}
